<style>
  .merah{color:red}
  .hijau{color:green}
  .kuning{color:orange}
  .biru{color:blue}
  .ungu{color:purple}
  .gradasi-biru{
    background:linear-gradient(#eef,#ccf)
  }
  .gradasi-toska{
    background:linear-gradient(#eff,#cff)
  }
  .gradasi-hijau{
    background:linear-gradient(#efe,#cfc)
  }
  .gradasi-merah{
    background:linear-gradient(#fee,#fcc)
  }
  .gradasi-kuning{
    background:linear-gradient(#ffe,#ffc)
  }

</style>